[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# sender="${PRIVATE_KEY}" , not needed if you run deploy with --private-key

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
